apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsinstances.jenkins.jenkinsoperator.maratoid.github.com
spec:
  group: jenkins.jenkinsoperator.maratoid.github.com
  names:
    kind: JenkinsInstance
    plural: jenkinsinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminemail:
              type: string
            adminsecret:
              type: string
            agentport:
              format: int32
              type: integer
            config:
              type: string
            env:
              type: object
            executors:
              format: int32
              type: integer
            image:
              pattern: .+:.+
              type: string
            jobspvc:
              type: string
            location:
              type: string
            masterport:
              format: int32
              type: integer
            plugins:
              items:
                properties:
                  id:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            pullpolicy:
              type: string
            replicas:
              format: int32
              type: integer
            servicetype:
              type: string
          type: object
        status:
          properties:
            adminsecret:
              type: string
            api:
              type: string
            phase:
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
