apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsplugins.jenkins.jenkinsoperator.maratoid.github.com
spec:
  group: jenkins.jenkinsoperator.maratoid.github.com
  names:
    kind: JenkinsPlugin
    plural: jenkinsplugins
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            jenkinsinstance:
              type: string
            pluginconfig:
              type: string
            pluginid:
              type: string
            pluginversion:
              type: string
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
