apiVersion: jenkins.jenkinsoperator.maratoid.github.com/v1alpha1
kind: JenkinsJob
metadata:
  name: from-custom-resource-xml
spec:
  jenkinsinstance: jenkinsinstance-example
  jobxml: |
    <?xml version="1.0" encoding="UTF-8"?><project>
        <actions/>
        <description>Job created from custom resource from XML</description>
        <keepDependencies>false</keepDependencies>
        <properties/>
        <scm class="hudson.scm.NullSCM"/>
        <canRoam>true</canRoam>
        <disabled>false</disabled>
        <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
        <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
        <triggers/>
        <concurrentBuild>false</concurrentBuild>
        <builders>
            <hudson.tasks.Shell>
                <command>echo Hello World with xml!</command>
            </hudson.tasks.Shell>
        </builders>
        <publishers/>
        <buildWrappers/>
        <displayName>From custom resource XML</displayName>
    </project>
