apiVersion: jenkins.jenkinsoperator.maratoid.github.com/v1alpha1
kind: JenkinsPlugin
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsplugin-sample
spec:
  name: credentials
  pluginid: credentials
  pluginversion: latest
  jenkinsinstance: jenkinsinstance-sample
  pluginconfig: |
        import jenkins.*
        import hudson.*
        import hudson.model.*
        import jenkins.model.*
        import com.cloudbees.plugins.credentials.impl.*;
        import com.cloudbees.plugins.credentials.*;
        import com.cloudbees.plugins.credentials.domains.*;

        Credentials githubScanCreds = (Credentials) new UsernamePasswordCredentialsImpl(
          CredentialsScope.GLOBAL,
          "github-access",
          "github-access",
          "githubuser",
          "githubpassword")

        SystemCredentialsProvider.getInstance().getStore().addCredentials(
          Domain.global(),
          githubScanCreds)
