apiVersion: jenkins.jenkinsoperator.maratoid.github.com/v1alpha1
kind: JenkinsInstance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsinstance-sample
spec:
  image: "jenkins/jenkins:lts"
  name: operatedjenkins
  env:
    SOME_ENV: "test"
  plugins:
    - id: greenballs
      version: "1.15"
  annotations:
    cnct.io/annotation: "test"
    cnct.io/other-annotation: "other test"
  executors: 2
  replicas: 1
  adminsecret: jenkins-test
  location: https://jenkins.example.com
  adminemail: admin@example.com
  service:
    name: jenkins
    servicetype: NodePort
    annotations:
      cnct.io/service-annotation: "test"
      cnct.io/other-service-annotation: "other test"
  ingress:
    annotations:
      cnct.io/ingress-annotation: "test"
      cnct.io/other-ingress-annotation: "other test"
    service: jenkins
    path: /
  serviceaccount:
    name: jenkins
  networkpolicy: true
  storage:
    jobspvc: jenkins
    jobspvcspec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

