{{- if .Values.rbac }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins-operator.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "jenkins-operator.name" . }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jenkins-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jenkins-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jenkins-operator.name" . }}
  namespace: {{ .Release.Namespace}}
{{- end }}